- name: copy module
  hosts: ansible
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/my project/Dockerfile
        dest: /home/ec2-user
        mode: '0644'



    - name: Run the Linux command
      ansible.builtin.command:
        cmd: docker build -t sarathii .

    - name: remove previous container
      ansible.builtin.command:
        cmd: docker rm -f prakash

    - name: run docker 
      ansible.builtin.command:
        cmd: docker run -itd --name prakash -p 8083:8080 sarathii

    - name: exec1
      ansible.builtin.command:
        cmd: docker exec -it prakash
    - name: copy to containner
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/newproject/target
        dest: /home/ec2-user
    - name: copy target
        shell: docker cp /home/ec2-user/prakash:/var/lib/docker/







    

    




