- name: copy module
  hosts: ansible
  become: true
  ignore_errors: yes
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: jenkins.sh
        dest: /home/ec2-user
        mode: '0644'

    - name: copy jenkins
      shell: docker cp /home/ec2-user/jenkins.sh prakash:/home
    - name: permission
      command: docker exec -it prakash chmod +x /home/jenkins.sh

    - name: run script
      shell: docker exec -it prakash bash -c ". /home/jenkins.sh"







    

    
